name: 🐛 Bug Report
description: Report a reproducible bug
labels:
  - requires triage
  - bug
body:
  - type: markdown
    attributes:
      value: |-
        Have a question? This is the `manzoni-app` issue tracker – and is not the right place for general support or questions.
        Instead, use [`manzoni-app` GitHub Discussions](https://github.com/gems-platforms/manzoni-app/discussions) to get support or ask questions.
  - type: input
    id: description
    attributes:
      label: Issue description
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: >-
        A clear and concise description of what actually happened.
        Please wrap any error messages or output in code tags, instead of images.
        Please attach logs if relevant.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |-
        Issues without reproduction steps or code examples may be closed as not actionable.
        Please try to provide a Minimal, Complete, and Verifiable example ([link](http://stackoverflow.com/help/mcve)), including a link to the model file you used if possible.
      placeholder: >-
        Please try to provide a Minimal, Complete, and Verifiable example.
        http://stackoverflow.com/help/mcve
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: My Environment
      description: |-
        Please also add any other relevant dependencies to this table at the end. For example: Electron, node-llama-cpp, Webpack.
      value: |
        | Dependency               | Version             |
        | ---                      | ---                 |
        | Operating System         |                     |
        | CPU                      | Intel i9 / Apple M1 |
        | Node.js version          | x.y.zzz             |
        | Typescript version       | x.y.zzz             |
        | Manzoni version | x.y.zzz             |
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >-
        Add any other context about the bug report here.
  - type: dropdown
    id: pr
    attributes:
      label: Are you willing to resolve this issue by submitting a Pull Request?
      options:
        - Yes, I have the time, and I know how to start.
        - >-
          Yes, I have the time, but I don't know how to start. I would need
          guidance.
        - >-
          No, I don’t have the time, but I can support (using donations)
          development.
        - >-
          No, I don’t have the time and I’m okay to wait for the community /
          maintainers to resolve this issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        First-time contributors are always welcome! 🙌

        👋 Have a great day and thank you for the bug report!
